In [19]:
#DwikaPrilando
#PSTI B



x = 32 #uat variabel skalar x dan simpan suatu nillai skalar

In [3]:
type(x) #tampilkan tipe data dari x

int

In [4]:
y = 20 #buat variabel skalar y dan simpan suatu nilai skalar

type(y) #tampilkan tipe data dari y
g = x + y #jumlahkan x+y

print(g) #Tampilkan hasil penjumlahan

52


In [7]:
x_float = 30.5

j = x_float + y
print(j)

type(x_float)

50.5


float

In [9]:
import tensorflow as t




In [15]:
x_pt = t.constant(25)
x_pt

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [16]:
x_pt.shape

TensorShape([])

In [ ]:
y_tf = t.Variable(3, dtype=t.int16)

In [29]:
x_tf = t.Variable(3, dtype=t.int8)

In [30]:
x_tf + t.cast(y_tf, t.int8)

<tf.Tensor: shape=(), dtype=int8, numpy=6>

In [34]:
tf_sum = t.add(x_tf, t.cast(y_tf, t.int8))
tf_sum

<tf.Tensor: shape=(), dtype=int8, numpy=6>

In [35]:
tf_sum.numpy() # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

np.int8(6)

In [36]:
type(tf_sum.numpy())

numpy.int8

In [40]:
tf_float = t.Variable(25., dtype=t.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>